### PR TITLE
README.md: minor consistency changes & typo fixes

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by yuin** [comment]
Fixing typo is OK. But I prefer setext headings to atx headings.

**Comment by XhmikosR** [comment]
You still had ATX ones. No big deal.

**Comment by yuin** [comment]
In CommonMark, setext headings are only supported in level1 and level2. So I use ATX headings for level3 or more.

**Comment by XhmikosR** [comment]
No problem, I just use ATX for everything because it's clearer to me.

**Pull request closed without merging**
